# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build docker and run tests
        run: "docker-compose -f docker-compose.yml -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from e2e"

      - name: Get allure history
        uses: peaceiris/actions-gh-pages@v2
        if: always()
        continue-on-error: true
        with:
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Setup allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

        # Need to enable IMAP for this step to success
        # https://support.google.com/mail/answer/7126229?hl=en
        # And allow less secure apps
        # https://myaccount.google.com/lesssecureapps
        # Display unlock captcha
        # https://accounts.google.com/b/0/DisplayUnlockCaptcha
      
